server:
  port: 8080

spring:
  application:
    name: text-to-sql
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.yaml

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/text_sql_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always

  ai:
    openai:
      api-key: ${SPRING_AI_OPENAI_API_KEY:dummy-key}
      base-url: ${SPRING_AI_OPENAI_BASE_URL:http://localhost:11434/v1}
      chat:
        options:
          model: ${SPRING_AI_OPENAI_MODEL:llama3}
          temperature: 0.0

logging:
  level:
    ru.saratov.texttosql: DEBUG
    org.springframework.ai: DEBUG

  file:
    name: logs/text-to-sql.log